export const CONFIG = {
  FOOTBALL_DATA_TOKEN: "39c4347bf04d4123809d0049efe4d3a5",
  CLAUDE_API_KEY: "",
  CLAUDE_MODEL: "claude-sonnet-4-6",
  FOOTBALL_DATA_BASE: "https://api.football-data.org/v4",
  WC_COMPETITION_ID: 2000,
};

export const PESOS_DEFAULT = {
  estadistico: 0.60,
  psicologico: 0.40,
  categorias: {
    presion: 0.14,
    local: 0.10,
    liderazgo: 0.10,
    momentum: 0.06
  }
};

export const ESTADIOS_ALTITUD = {
  "BMO Field": 76,
  "BC Place": 5,
  "Commonwealth Stadium": 671,
  "MetLife Stadium": 3,
  "SoFi Stadium": 30,
  "AT&T Stadium": 198,
  "NRG Stadium": 15,
  "Levi's Stadium": 13,
  "Hard Rock Stadium": 2,
  "Lumen Field": 5,
  "Arrowhead Stadium": 319,
  "Lincoln Financial Field": 20,
  "Gillette Stadium": 12,
  "Mercedes-Benz Stadium": 320,
  "Estadio Azteca": 2240,
  "Estadio Akron": 1566,
  "Estadio BBVA": 537,
};

export const EQUIPOS_FLAGS = {
  "Canada": "🇨🇦",
  "Bosnia and Herzegovina": "🇧🇦",
  "Qatar": "🇶🇦",
  "Switzerland": "🇨🇭",
  "Mexico": "🇲🇽",
  "South Africa": "🇿🇦",
  "Korea Republic": "🇰🇷",
  "Czechia": "🇨🇿",
  "Argentina": "🇦🇷",
  "Chile": "🇨🇱",
  "Slovakia": "🇸🇰",
  "New Zealand": "🇳🇿",
  "USA": "🇺🇸",
  "Paraguay": "🇵🇾",
  "Ecuador": "🇪🇨",
  "Wales": "🏴󠁧󠁢󠁷󠁬󠁳󠁿",
  "Spain": "🇪🇸",
  "Serbia": "🇷🇸",
  "Morocco": "🇲🇦",
  "Panama": "🇵🇦",
  "Brazil": "🇧🇷",
  "Germany": "🇩🇪",
  "Colombia": "🇨🇴",
  "Saudi Arabia": "🇸🇦",
  "France": "🇫🇷",
  "Portugal": "🇵🇹",
  "Senegal": "🇸🇳",
  "Cameroon": "🇨🇲",
  "England": "🏴󠁧󠁢󠁥󠁮󠁧󠁿",
  "Netherlands": "🇳🇱",
  "Uganda": "🇺🇬",
  "Japan": "🇯🇵",
  "Croatia": "🇭🇷",
  "Ireland": "🇮🇪",
  "Ghana": "🇬🇭",
  "Belgium": "🇧🇪",
  "Uruguay": "🇺🇾",
  "Iran": "🇮🇷",
  "Costa Rica": "🇨🇷",
  "Denmark": "🇩🇰",
  "Turkey": "🇹🇷",
  "Australia": "🇦🇺",
  "El Salvador": "🇸🇻",
  "Norway": "🇳🇴",
  "Poland": "🇵🇱",
  "Algeria": "🇩🇿",
  "Guatemala": "🇬🇹",
};
